language: go
go:
  - 1.x
install:
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/dave/courtney
  - go get -t -v ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - goveralls -coverprofile=coverage.out -service=travis-ci